### ISSUE TITLE
Hide the search

### ISSUE THREAD

**Issue by yzy0806** [Earthlapse/data-visualization-tools#1]

**Comment by Lidaron** [comment]
@yzy0806 I created 9b50ae25b8d47674d8a0982054d698b726431696 which I tested with some local code. It should be sufficient for the search box. Can you check its compatibility with the full software?

**Comment by yzy0806** [comment]
@Lidaron
Somehow I don't have the writing permission on the external hard drive and therefore cannot test it. Do you have any ways to bypass this permission measure?

**Comment by Lidaron** [comment]
@yzy0806 If memory serves, there's a switch on the hard drive that enables R/W mode; have you checked that out? Also, you might have to unset the Readonly attribute on some files.

**Comment by yzy0806** [comment]
The switch on the hard drive is to turn on/off the hard drive. I try to
disable the readonly but it says i do not have the permission.

On Sat, Mar 12, 2016 at 9:27 PM, Brian Xu notifications@github.com wrote:

> @yzy0806 https://github.com/yzy0806 If memory serves, there's a switch
> on the hard drive that enables R/W mode; have you checked that out? Also,
> you might have to unset the Readonly attribute on some files.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Earthlapse/data-visualization-tools/issues/1#issuecomment-195854208
> .

## 

Leo Ying
Information Systems\* | *Human Computer Interaction
Carnegie Mellon University
(904)-514-3510
yzy0806@gmail.com

**Comment by Lidaron** [comment]
One more thing to check: Is the file system NTFS? If so, you might need to go into file properties' Security tab, take ownership, and allow full control for the Everyone principal.

**Comment by yzy0806** [comment]
The take ownership tab is greyed out. I will go to CREATE LAB tomorrow to
resolve this issue.

On Sat, Mar 12, 2016 at 11:05 PM, Brian Xu notifications@github.com wrote:

> One more thing to check: Is the file system NTFS? If so, you might need to
> go into file properties' Security tab, take ownership, and allow full
> control for the Everyone principal.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Earthlapse/data-visualization-tools/issues/1#issuecomment-195864739
> .

## 

Leo Ying
Information Systems\* | *Human Computer Interaction
Carnegie Mellon University
(904)-514-3510
yzy0806@gmail.com
